# Generated by Django 3.2.4 on 2021-07-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210705_1432'),
    ]

    operations = [

        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
